---
title: "Security Research Blog"
description: "Advanced cybersecurity research and vulnerability analysis"
baseurl: "/Sisu-Sus-Stop/"
url: "https://sisu-sus.github.io"

author:
  name: "Sisu-Sus"
  email: "fixitdunbreakit@gmail.com"
  bio: "Security researcher specializing in web app security"
  location: "Global"
title: "Security Research Blog"
description: "Advanced cybersecurity research and vulnerability analysis"
baseurl: "/Sisu-Sus-Stop/"
url: "https://sisu-sus.github.io"

author:
  name: "Sisu-Sus"
  email: "fixitdunbreakit@gmail.com"
  bio: "Security researcher specializing in web app security"
  location: "Global"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

remote_theme: "pages-themes/hacker"

  collections:
    research:
      output: true
      permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sisu-Sus"
  - scope:
      path: "_research"
      type: "research"
    values:
      layout: "default"
      author: "Sisu-Sus"
      
future: false
show_drafts: false
---











      
